// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2xFiU9B046EO6LZyo3NCsZy0SM6FgxvQ',
    appId: '1:180841657176:web:763527fcf32ea44c54ab2d',
    messagingSenderId: '180841657176',
    projectId: 'crashlytics-347a5',
    authDomain: 'crashlytics-347a5.firebaseapp.com',
    storageBucket: 'crashlytics-347a5.firebasestorage.app',
    measurementId: 'G-2WQ7ZTXLDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjFcZet6o6Hsjdbrf_c7iz1MuirYWqHUM',
    appId: '1:180841657176:android:51447e759250fef354ab2d',
    messagingSenderId: '180841657176',
    projectId: 'crashlytics-347a5',
    storageBucket: 'crashlytics-347a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ri_PGgJ87YWQ77h43Z3isZ2ew4aUvZc',
    appId: '1:180841657176:ios:dfd64a321ddd6d9954ab2d',
    messagingSenderId: '180841657176',
    projectId: 'crashlytics-347a5',
    storageBucket: 'crashlytics-347a5.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ri_PGgJ87YWQ77h43Z3isZ2ew4aUvZc',
    appId: '1:180841657176:ios:dfd64a321ddd6d9954ab2d',
    messagingSenderId: '180841657176',
    projectId: 'crashlytics-347a5',
    storageBucket: 'crashlytics-347a5.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2xFiU9B046EO6LZyo3NCsZy0SM6FgxvQ',
    appId: '1:180841657176:web:54f4f2636ee55cb954ab2d',
    messagingSenderId: '180841657176',
    projectId: 'crashlytics-347a5',
    authDomain: 'crashlytics-347a5.firebaseapp.com',
    storageBucket: 'crashlytics-347a5.firebasestorage.app',
    measurementId: 'G-4GW0L9LKJ5',
  );
}
